[versions]
cca = "5.3.0"
elmendorf = "0.12.0"
fpa = "0.2-SNAPSHOT"
mcAnnotations = "1.0"
modmenu = "8.0.0-beta.2"

[libraries]
cca-base = { module = "dev.onyxstudios.cardinal-components-api:cardinal-components-base", version.ref = "cca" }
cca-entity = { module = "dev.onyxstudios.cardinal-components-api:cardinal-components-entity", version.ref = "cca" }
elmendorf = { module = "org.ladysnake:elmendorf", version.ref = "elmendorf" }
mcAnnotations = { module = "com.demonwav.mcdev:annotations", version.ref = "mcAnnotations" }
modmenu = { module = "com.terraformersmc:modmenu", version.ref = "modmenu"}
permissionsApi = { module = "me.lucko:fabric-permissions-api", version.ref = "fpa" }