[versions]
cca = "5.3.0"
elmendorf = "0.12.0"
emi = "1.0.23+1.20.2"
fpa = "0.2-SNAPSHOT"
mcAnnotations = "1.0"
modmenu = "8.0.0-beta.2"
rei = "13.0.666"

[libraries]
cca-base = { module = "dev.onyxstudios.cardinal-components-api:cardinal-components-base", version.ref = "cca" }
cca-entity = { module = "dev.onyxstudios.cardinal-components-api:cardinal-components-entity", version.ref = "cca" }
elmendorf = { module = "org.ladysnake:elmendorf", version.ref = "elmendorf" }
emi = { module = "dev.emi:emi-fabric", version.ref = "emi" }
mcAnnotations = { module = "com.demonwav.mcdev:annotations", version.ref = "mcAnnotations" }
modmenu = { module = "com.terraformersmc:modmenu", version.ref = "modmenu"}
permissionsApi = { module = "me.lucko:fabric-permissions-api", version.ref = "fpa" }
rei-api = { module = "me.shedaniel:RoughlyEnoughItems-api-fabric", version.ref = "rei" }
